### ISSUE TITLE
pyinn

### ISSUE THREAD

**Issue by amatii** [pclucas14/lidar_generation#10]
is there any way to remove pyinn? it takes a long time to install it on colab (more than 20mins), and also the package is no longer being updated. apparently, the new version of pytorch does not need pyinn.

**Comment by pclucas14** [comment]
Hi, 

no you should not need it anymore. It was for chamfer and EMD losses, but I'm sure you can find newer and better wrappers. [Here](https://github.com/chrdiller/pyTorchChamferDistance) is one for Chamfer
