### ISSUE TITLE
lidar.npz

### ISSUE THREAD

**Issue by amatii** [pclucas14/lidar_generation#11]
I am trying to repeat your result on Colab.
However, the original lidar.npz is large (+6G bytes), and when I am trying to np.load it, the Colab machine run out of memory, and stop uploading it.

is it possible to upload a smaller version of lidar.npz on the repo, e.g. 2 G? 
of course, the result will not be as good as training on the whole data, but more practical.

**Comment by pclucas14** [comment]
Hi, 

I built a per recording version of the dataset, yo can find it [here ](https://github.com/pclucas14/processed-kitti-lidar)

Yo can also try to load the `lidar.npz` file on your home computer and make a smaller version of it.

-Lucas
