### ISSUE TITLE
Question regarding preprocessing and 2d transformation

### ISSUE THREAD

**Issue by jo-jstrm** [pclucas14/lidar_generation#16]
Hey all,
thanks for your great paper! We are currently trying out an approach based on your 2d representation of the point clouds. 

While implementing this, I wondered which steps you took for preprocessing raw point clouds. As I currently understand your code (and your answers to previous questions), I would need to transform a point cloud to a format of shape (number_of_points, 3) (according to line 141 in parse_velo.py) and then apply `process_velo()` in parse_velo.py on each point cloud. This yields the 2d representation you discussed in the paper, is that correct?

Best

**Comment by pclucas14** [comment]
Hi, 

yes I think that is generally correct. If you are planning on using the KITTI dataset, please consider using the already transformed data [here](https://github.com/pclucas14/processed-kitti-lidar). 
If you need the raw files, I would advise either reimplementing the processing code, or making sure it works as you expect it to work (I haven't played with it in a few years)

Best, 
Lucas

**Comment by jo-jstrm** [comment]
Thank your very much for taking the time to answer! We will use not only KITTI data and want to create an on-line processing pipeline, so I need to include the preprocessing. The preprocessing code is a bit unintuitive due to all the list operations, so I thought I'd better verify my assumptions by asking here ;)

I tried it as described above, and your code worked (almost) out of the box for me. Still got to verify the transformation results, though. But as the shape of the result looks exactly as expected, I am quite optimistic that the rest is correct as well :)

May I ask how you tested your code? We currently plan on calculating some small transformations by hand in order to verify the preprocessing results.

**Comment by pclucas14** [comment]
I spent a lot of time displaying the graphs, looking specifically at preprocessed runs `remove_zeros` was taking a lot of iterations to converge

**Comment by jo-jstrm** [comment]
Thank you very much!
