### ISSUE TITLE
In preprocessing, why discard top and bottom rows?

### ISSUE THREAD

**Issue by jo-jstrm** [pclucas14/lidar_generation#17]
Hey again!

In [`parse_velo.process_velo() `](https://github.com/pclucas14/lidar_generation/blob/2a2c8bce1ce23a338291778e8735ada23dd2fe9d/kitti_data/parse_velo.py#L94) you discard the uppermost two and the lowest rows (lines) of the data `lines = lines[2:-1]`. 

What was the reason for that? I see that you discard more rows in [`utils.preprocess()`](https://github.com/pclucas14/lidar_generation/blob/2a2c8bce1ce23a338291778e8735ada23dd2fe9d/utils.py#L151), so why do not drop the aforementioned rows there and keep them during preprocessing in `parse_velo.process_velo() `?

I think it could have to with the discarded measurements tending to be bad in KITTI?

Best
Jo

**Comment by pclucas14** [comment]
Hi, 

good question. I'm guessing that these rows had a lot more missing values than other rows, and were not carrying any useful info so I dropped them. 

Regarding your second question, I do not recall what exactly I did in there, sorry!
