### ISSUE TITLE
Regarding mayavi code for visulaizing Lidar in preprocessed  from [2,40,256] format

### ISSUE THREAD

**Issue by prashkmr** [pclucas14/lidar_generation#18]
Dear Lucas,

Your visualizations are very impressive. I was using mayavi for visualizations for preprocessed LiDAR point cloud in the preprocessed format. Could you share the scripts you had used to visulaized the reconstructed [2,40,256] range image as a point cloud as seen in your paper. I would really love to us them. They look extra clear and crisp. 

Requesting your help here.

-Prashant

**Comment by pclucas14** [comment]
Hi Prashant, 

To convert from polar representation to (x,y,z) space, you can use the methor `from_polar` or `from_polar_np` if you have a numpy array. You can find them [here](https://github.com/pclucas14/lidar_generation/blob/master/utils.py#L57). Once that is done, you can visualize the point cloud using the mayavi package, as I do in the method `show_pc` which you can find [here](https://github.com/pclucas14/lidar_generation/blob/master/utils.py#L183).

Once you have generated the images and saved them as separate files, You can look at cell [25] [of this notebook](https://github.com/pclucas14/lidar_generation/blob/master/graph_maker.ipynb)

That's the general approach. Note that this is some pretty old code, so you may have to give it a bit of love to make it work. 

Happy Holidays, 
Lucas
