### ISSUE TITLE
What does the dimension of data mean?

### ISSUE THREAD

**Issue by GilgameshD** [pclucas14/lidar_generation#7]
Hi, thanks for your outstanding work! I notice that the output dimension of the model is (ns, 2, 40, 256), could you explain more about the last three numbers ? Thanks a lot!

**Comment by pclucas14** [comment]
Hi, 

please have a look at this issue https://github.com/pclucas14/lidar_generation/issues/2. 

If you still need clarifications let me know

**Comment by GilgameshD** [comment]
Thanks!
