### ISSUE TITLE
Why two separate maxpools for R, Z channel in remove_zeros function in utils.py ?

### ISSUE THREAD

**Issue by sabyasachis** [pclucas14/lidar_generation#8]
I think we use the mapool operation in remove_zeros function to replace the zeros in range image with nearest max value. I can't understand the motivation for two separate maxpools for R and Z channel. Isn't it important that we apply one maxpool on both the channels so that same nearest lidar point in R and Z channel is used to fill the zeros?

**Comment by pclucas14** [comment]
Hi, 

(I would need to verify with the current code but) the max pool operation operates independently on channels, meaning that the two max pools operations on two tensors of shape `(1, H, W)` would be equivalent as a single maxpool on the concatenated tensors `(2, H, W)` and then splitting them

**Comment by sabyasachis** [comment]
That's correct. But shouldn't we fill zeros with the same nearest pixel for both the channels instead of trying to fill both the channels separately.

I think with current code, it may so happen that the zeros are filled by R and Z values from different pixels and such a filled point may not exist in the point cloud. Can this not contribute to some error in model training?

**Comment by pclucas14** [comment]
You may be right. However I think that by design if a point is lacking R it will also be lacking Z. But I agree that this procedure could be better.

**Comment by sabyasachis** [comment]
Thank you for clarification.
