### ISSUE TITLE
veriosn of libraries

### ISSUE THREAD

**Issue by amatii** [pclucas14/lidar_generation#9]
I am trying to repeat your result on Colab.
I am getting many errors, probably because of mismatch between the version of libraries you used, and the one I have. I tried, and tried, and tried, but still getting errors.

can you make a requirement.txt file?

**Comment by pclucas14** [comment]
Hi, 

It's been a while since I ran this code, I'm not sure exactly in which env I did it in. There's not many requirements, apart form torch and torchvision. Can yo tell me which package you are having trouble with ?

**Comment by pclucas14** [comment]
closing the issue, feel free to reopen if needs be
